hardcore:
  world: "world"

messages:
  death_ban: "&cYou died in hardcore mode. You are banned from this server."
  info: "&6This server uses &eZeroRespawn &6hardcore rules. Die once, and you're done."
